services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    environment:
      FLASK_APP: app.app:create_app
      FLASK_ENV: development
      DB_URL: postgresql://admin:admin@postgres-db:5432/cctdb
    volumes:
      - .:/app:ro
    command: flask run --host=0.0.0.0 --port=3000
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cctdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
